# Generated by Django 5.0.4 on 2024-04-21 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300, verbose_name='Тема письма')),
                ('message', models.TextField(verbose_name='Тело сообщения')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='время старта')),
                ('end_time', models.DateTimeField(verbose_name='время окончания')),
                ('period', models.CharField(choices=[('daily', 'ежедневная'), ('weekly', 'еженедельная'), ('monthly', 'ежемесячная')], default='daily', max_length=30, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('created', 'запущена'), ('started', 'создана'), ('done', 'завершена')], default='created', max_length=30, verbose_name='Статус')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.mailingmessage', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
