# Generated by Django 5.0.4 on 2024-04-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_owner_mailingsettings_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='status',
            field=models.CharField(choices=[('created', 'создана'), ('started', 'запущена'), ('done', 'завершена')], default='created', max_length=30, verbose_name='Статус'),
        ),
    ]
