# Generated by Django 5.0.4 on 2024-04-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_client_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('set_is_activate', 'can change active')], 'verbose_name': 'Настройка', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активно'),
        ),
    ]
